.catalog:
  version: 1
  questions:
    - variable: SITE_DNAME
      description: Specify the domain name of the site.
      label: Site domain name
      required: true
      default: projectname.portal.siemonster.com
      type: string

es-data-node:
  scale: 2


