version: '2'
services:
  msa:
    labels:
      io.rancher.sidekicks: msa-volume
      io.rancher.container.pull_image: always
    tty: true
    volumes_from:
      - msa-volume
    build: http://proxy.git-proxy/git@github.com:siemonster/Project.git#master:containers/msa
    environment:
      ADDITIONAL_PREPARE_COMMAND: 'echo ''db.getCollection("_sites").update({_id:"siemonster"}, {$$set: {names:["admin.${SITE_DNAME}","${SITE_DNAME}"]}})'' | mongo mongo-sites'
    stdin_open: true
  msa-volume:
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
    tty: true
    volumes:
      - /var/lib/mongodb
    build: http://proxy.git-proxy/git@github.com:siemonster/Project.git#master:containers/msa-volume
    stdin_open: true
    command: /bin/bash
  siemonster:
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
    tty: true
    environment:
      SITE_DNAME: ${SITE_DNAME}
    build: http://proxy.git-proxy/git@github.com:siemonster/Project.git
    stdin_open: true
  heaven-backend:
   image: rancher/dns-service
   links:
   - siemonster

