siemonster:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
  environment:
    SITE_NAME: ${SITE_NAME}
    SITE_REF_NAME: ${SITE_REF_NAME}
    MSA_URL: ${MSA_URL}
    MSA_SKEY: ${MSA_SKEY}
  build: ${APP_REPO_URL}
  stdin_open: true
  heaven-backend:
   image: rancher/dns-service
   links:
   - siemonster