.catalog:
  version: 1
  questions:
    - variable: SITE_DNAME
      description: Specify the domain name of the site.
      label: Site domain name
      required: true
      default: siemonster1.siemonster.com
      type: string
siemonster:
  scale: 1
  version: 1
  health_check:
    port: 80
    interval: 2000
    initializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: GET "/" "HTTP/1.0"
    healthy_threshold: 2
    response_timeout: 2000
msa-volume:
  scale: 1
msa:
  scale: 1
