version: '2'
services:

  es-client:
    cap_add:
    - IPC_LOCK
    ulimits:
      nofile: 65536
      memlock: -1
    mem_limit: 2102410241024
    memswap_limit: 2102410241024
    image: ikuturso/siemonster-alpine-es
    environment:
      ES_HEAP_SIZE: 1g
      ES_JAVA_OPTS: -Dmapper.allow_dots_in_name=true
    command: >
      -Des.bootstrap.mlockall=true
      -Des.network.publish_host=0.0.0.0
      -Des.network.host=_eth0_
      -Des.discovery.zen.ping.multicast.enabled=false
      -Des.node.name="node-capricorn"
      -Des.cluster.name="siemonster"
      -Des.discovery.zen.minimum_master_nodes=2
      -Des.discovery.zen.ping.unicast.hosts="es-data-node1 es-data-node2"
      -Des.index.number_of_shards=1
      -Des.index.refresh_interval=10s
      -Des.index.translog.flush_threshold=20000
      -Des.action.auto_create_index=true
      -Des.action.disable_delete_all_indices=true
      -Des.node.data=false
    hostname: capricorn

  es-data-node1:
    volumes:
    - /usr/share/elasticsearch/data
    cap_add:
    - IPC_LOCK
    ulimits:
      nofile: 65536
      memlock: -1
    mem_limit: 4102410241024
    memswap_limit: 4102410241024
    environment:
      ES_HEAP_SIZE: 2g
    image: ikuturso/siemonster-alpine-es
    command: >
      -Des.bootstrap.mlockall=true
      -Des.discovery.zen.ping.multicast.enabled=false
      -Des.node.name="node-kraken"
      -Des.cluster.name="siemonster"
      -Des.discovery.zen.minimum_master_nodes=2
      -Des.discovery.zen.ping.unicast.hosts="$protip, $tiamip"
      -Des.cluster.routing.allocation.awareness.attributes=disk_type
      -Des.node.disk_type=ssd
      -Des.node.data=true
      -Des.index.number_of_shards=3
      -Des.index.refresh_interval=10s
      -Des.index.translog.flush_threshold=20000
      -Des.action.auto_create_index=true
      -Des.action.disable_delete_all_indices=true
      -Des.threadpool.bulk.queue_size=500

  es-data-node2:
    volumes:
    - /usr/share/elasticsearch/data
    cap_add:
    - IPC_LOCK
    ulimits:
      nofile: 65536
      memlock: -1
    mem_limit: 4102410241024
    memswap_limit: 4102410241024
    environment:
      ES_HEAP_SIZE: 2g
    image: ikuturso/siemonster-alpine-es
    command: >
      -Des.bootstrap.mlockall=true
      -Des.discovery.zen.ping.multicast.enabled=false
      -Des.node.name="node-kraken"
      -Des.cluster.name="siemonster"
      -Des.discovery.zen.minimum_master_nodes=2
      -Des.discovery.zen.ping.unicast.hosts="$protip, $tiamip"
      -Des.cluster.routing.allocation.awareness.attributes=disk_type
      -Des.node.disk_type=ssd
      -Des.node.data=true
      -Des.index.number_of_shards=3
      -Des.index.refresh_interval=10s
      -Des.index.translog.flush_threshold=20000
      -Des.action.auto_create_index=true
      -Des.action.disable_delete_all_indices=true
      -Des.threadpool.bulk.queue_size=500

#  es2graphite:
#    labels:
#      io.rancher.container.pull_image: always
#      io.rancher.container.hostname_override: container_name
#    tty: true
#    stdin_open: true
#    links:
#    - es-client
#    - health
#    environment:
#      ELASTICSEARCH_ADDR: es-client
#      GRAPHITE: health
#      GRAPHITE_PREFIX: PROD.Elasticsearch
#      INTERVAL_SECONDS: 20
#      BULK_SIZE: 10
#    image: logzio/es2graphite

  kibana:
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
    tty: true
    stdin_open: true
    links:
    - es-client:elasticsearch
    build: http://proxy.git-proxy/git@github.com:siemonster/Project.git#master:containers/kibana

  reporting:
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: reporting-volume
    tty: true
    stdin_open: true
    volumes_from:
    - reporting-volume
    links:
    - es-client:es-client
    - kibana:sm-kibana
    image: ikuturso/siemonster-reporting-4

  reporting-volume:
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
    tty: true
    stdin_open: true
    volumes:
    - /root/.local/share/data/bconf
    - /opt/skedler
    links:
    - es-client:es-client
    - kibana:sm-kibana
    build: http://proxy.git-proxy/git@github.com:siemonster/Project.git#master:containers/reporting-volume
    command: /bin/bash

